### ISSUE TITLE
(TEST-WEBPAGE-CHORDS-PNO-CHRD-FUN-EXAMP)

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken-RTs#2]
(TEST-WEBPAGE-CHORDS-PNO-CHRD-FUN-EXAMP) the last (equalp) statement returns nil. The listed pitches does not match up with what CMN displays.

Should it be: '((C4 (C4 D4 E4 F4) E4 F4 (D4 E4 F4 G4) (E4 F4 G4 A4) (F4 G4 A4 B4) C5) ?

**Comment by mdedwards** [comment]
So that's exactly the same list of pitches, right? Just an extra level of parentheses at the beginning?

That shouldn't work, if so. Can you try the test again, in isolation, after restarting lisp and loading the macros via (load "~/sc/test-suite/sc-test-suite-aux.lsp")

if it fails again, put a print in front of the failing loop and paste in here what it gives you

**Comment by danieljamesross** [comment]
Running it in isolation, it's now failing the (file-write-ok) test, which I haven't seen before.

When I put (print ) around the final loop I get '(C4 (C4 D4 E4 F4) E4 F4 (D4 E4 F4 G4) (E4 F4 G4 A4) (F4 G4 A4 B4) C5)

**Comment by mdedwards** [comment]
so that list of notes is exactly what equalp is testing against, which means it passes, right?

check out "/tmp/slippery-chicken-piece.eps": see if it opens and what size it has

**Comment by danieljamesross** [comment]
- ALL PIECE TESTS PASSED.
- METHOD AND FUNCTION TESTS NOT PERFORMED.
- ALL WEBPAGE EXAMPLE TESTS PASSED.

**Comment by mdedwards** [comment]
BINGO! Very nice to hear :)
